### ISSUE TITLE
Geo6 barks on non-existing postcode

### ISSUE THREAD

**Issue by jorotenev** [warreee/bpost-python-api#1]
If I pass postcode like `3333`,  here's what I get
```python
192.168.33.1 - - [21/Mar/2016 17:46:23] "GET /order/bpost_offices/3333 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/app/order/views.py", line 96, in bpost_addresses
    addresses = g.getNearestServicePoints(postcode)
  File "/usr/src/app/app/lib/bpost/GEO6/geo6.py", line 37, in getNearestServicePoints
    return self.__xmlAddressToBpostAddress(xml)
  File "/usr/src/app/app/lib/bpost/GEO6/geo6.py", line 42, in __xmlAddressToBpostAddress
    pois = poiList.findall("Poi")

```

Please fix lots thanks

**Comment by warreee** [comment]
Fixed, it returns an empty list now ;)
